AWSTemplateFormatVersion: "2010-09-09"

Description:
  A template for creating SSM parameters from a list of common parameters.

Resources:

  PostgresDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
        GroupDescription: Security Group for Postgres RDS
        SecurityGroupIngress:
            - SourceSecurityGroupId: !ImportValue webapp-security-group
              Description: 'Allowing connection to postgres port from webapp security group'
              FromPort: 5432
              IpProtocol: tcp
              ToPort: 5432
        Tags: 
            - Key: Name
              Value: rds-postgres-security-group
        VpcId: !ImportValue vpc

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: Subnet group for the database instances
      DBSubnetGroupName: employee-subnet-group
      SubnetIds: 
        - !ImportValue vpc-subnet-dbc
        - !ImportValue vpc-subnet-dba
        - !ImportValue vpc-subnet-dbb

  PostgresRDS:
    Type: AWS::RDS::DBInstance
    Properties: 
      AllocatedStorage: 20
      AvailabilityZone: !Select [0, !GetAZs '']
      BackupRetentionPeriod: 0
      DBInstanceClass: db.t2.micro
      DBClusterIdentifier: employee-cluster-group
      DBInstanceIdentifier: employee-db-instance-group
      DBName: "{{resolve:ssm:PostgresDb:1}}"
      DBSubnetGroupName: !Ref DBSubnetGroup
      DeleteAutomatedBackups: true
      DeletionProtection: false
      Engine: postgres
      EngineVersion: 10.14
      MasterUsername:  "{{resolve:ssm:PostgresUser:1}}"
      MasterUserPassword: '{{resolve:secretsmanager:PostgresRdsDbSecretPwd:SecretString:password}}'
      MultiAZ: false
      Port: 5432
      PubliclyAccessible: false
      StorageType: gp2
      Tags: 
        - Key: Name
          Value: employee-postgres-rds
      VPCSecurityGroups: 
        - !Ref PostgresDBSecurityGroup

Outputs:
  PostgresRDSEndpointAddress:
    Description: The end point address of the postgres RDS db
    Value: !GetAtt
      - PostgresRDS
      - Endpoint.Address
    Export:
      Name: postgres-rds-endpoint-address

  PostgresRDSEndpointPort:
    Description: The end point port of the postgres RDS db
    Value: !GetAtt
      - PostgresRDS
      - Endpoint.Port
    Export:
      Name: postgres-rds-endpoint-port