AWSTemplateFormatVersion: "2010-09-09"

Description:
    A template for creating SSM parameters from a list of common parameters.

Parameters:
    KeyName:
        Type: AWS::EC2::KeyPair::KeyName
        Description: "Name of an existing SSH Keypair to access the instance"
        Default: keypair

    InstanceAmiId:
        Description: An ec2 instance AMI id
        Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
        Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'        

    InstanceType:
        Type: String
        Description: The instance type for the ec2 host
        Default: "t2.micro"

    FlaskApp:
        Type: String
        Default: microblog.py

    PostgresUser:
        Type: String
        Default: employee_usr

    PostgresUrl:
        Type: String
        Default: POSTGRES_URL

    PostgresDb:
        Type: String
        Default: employee_db

    PostgresPwd:
        Type: String
        Default: employee
        NoEcho: 'true'

Resources:

  FlaskAppParam:
    Type: AWS::SSM::Parameter
    Properties: 
      DataType: text
      Description: Stores the postgres username
      Name: FlaskApp
      Type: String
      Value: !Ref FlaskApp

  UserParam:
    Type: AWS::SSM::Parameter
    Properties: 
      DataType: text
      Description: Stores the postgres username
      Name: PostgresUser
      Type: String
      Value: !Ref PostgresUser

  HostUrlParam:
    Type: AWS::SSM::Parameter
    Properties: 
      DataType: text
      Description: Stores the postgres host url
      Name: PostgresUrl
      Type: String
      Value: !Ref PostgresUrl

  DbNameParam:
    Type: AWS::SSM::Parameter
    Properties: 
      DataType: text
      Description: Stores the postgres db name
      Name: PostgresDb
      Type: String
      Value: !Ref PostgresDb

  Ec2InstanceTypeParam:
    Type: AWS::SSM::Parameter
    Properties: 
      DataType: text
      Description: Stores the ec2 instance type
      Name: Ec2InstanceType
      Type: String
      Value: !Ref InstanceType

  PasswordParam:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: Stores the postgres password
      Name: PostgresPwd
      SecretString: !Sub '"${PostgresPwd}"'