export vpcName="Custom VPC"
export routeTableName="$vpcName RouteTable"
export igwName="$vpcName IGW"
export EC2KEYPAIR="EC2SouthKP"
export AMIID="ami-7c87d913"
export NATAMIID="ami-0b3f4aad2015b0e15"
