#!/bin/bash

## Creating an SNS SQS stack for deploying an application for show casing fanout scenario

create-update-stack \
-s parent-sns-stack \
-t $HOME/aws-resources/scripts/cloudformation/templates/nested-templates/sns-project-parent-template.json \
-p $HOME/aws-resources/scripts/cloudformation/parameterfile/snsprojectprops.json \
-u $HOME/aws-resources/scripts/cloudformation/parameterfile/updatesnsprojectprops.json

status=$?

if [ ${status} = 0 ]
then
    echo "Starting application code deployment"

    $HOME/aws-resources/scripts/sqs-sns/code-deploy-using-github/code-deploy-github.ksh
fi
